export const ActionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    REMOVED_SELECTED_PRODUCT: 'REMOVED_SELECTED_PRODUCT',
    ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CHART',
    DELETE_PRODUCT_FROM_CART: 'DELETE_PRODUCT_FROM_CART',
};